include ./themes/tokyonight_moon.conf
# === FONTS ===
font_family      MesloLGSNFM-Regular
bold_italic_font MesloLGSNFM-Regular
font_size        15.0

# === WINDOW ===
initial_window_width  80
initial_window_height 25
window_resize_step_cells 1
hide_window_decorations yes
confirm_os_window_close 0

# === VISUAL ===
background_opacity 0.888
blur              yes

# === CURSOR ===
cursor_shape      block
cursor_blink      no

# === MOUSE ===
mouse_hide_wait   3.0
url_color         #4ea2f8

# === TERMINAL ===
term              xterm-256color

# === KEY BINDINGS ===
# Option key natural (no mapping)
macos_option_as_alt no

# === SCROLLBACK ===
scrollback_lines 10000

# === PERFORMANCE ===
repaint_delay    10
input_delay      3
sync_to_monitor  yes
