include ./themes/tokyonight_moon.conf
# === REMOTE ===
allow_remote_control yes

# === WINDOW ===
initial_window_width  80
initial_window_height 25
window_resize_step_cells 1
hide_window_decorations yes
confirm_os_window_close 0

# === VISUAL ===
background_opacity 0.95

# === CURSOR ===
cursor_shape      block

# === MOUSE ===
mouse_hide_wait   3.0
url_color         #4ea2f8

# === TERMINAL ===
term              xterm-256color

# === KEY BINDINGS ===
# Option key natural (no mapping)
macos_option_as_alt no

# === SCROLLBACK ===
scrollback_lines 10000

# === PERFORMANCE ===
repaint_delay    20
input_delay      3
sync_to_monitor  yes


# BEGIN_KITTY_FONTS
font_size 15.0
font_family      family="JetBrainsMonoNL Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
